use-grammars.only = [
  'xml',
  'json',
  'yaml',
  'toml',
  'html',
  'css',
  'markdown',
  'bash',
  'dart',
  'rust',
  'go',
  'python',
  'git-attributes',
  'git-commit',
  'git-config',
  'git-ignore',
  'git-rebase',
]
